/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package womomodel;


import java.util.List;
import womomodel.Fahrzeug_in_saison;
import womomodel.Mietfahrzeug;
import womomodel.Standort;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:50021/WoMoService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Fahrzeug {

    private int fahrgestellNr;
    private String marke;
    private int standort_idstandort;
    private String typ;
    private List<Fahrzeug_in_saison> fahrzeug_in_saison;
    private List<Mietfahrzeug> mietfahrzeugs;
    private Standort standort;

    /**
     * Constructor without parameter.
     * 
     */
    public Fahrzeug() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Fahrzeug(int fahrgestellNr) {
        this();
        this.fahrgestellNr = fahrgestellNr;
    }

   /**
    * Returns the value of the "fahrgestellNr" attribute.
    *
    * @return The value of the "fahrgestellNr" attribute.
    */
   public int getFahrgestellNr() {
      return fahrgestellNr;
   }
   /**
    * Returns the value of the "marke" attribute.
    *
    * @return The value of the "marke" attribute.
    */
   public String getMarke() {
      return marke;
   }
   /**
    * Returns the value of the "standort_idstandort" attribute.
    *
    * @return The value of the "standort_idstandort" attribute.
    */
   public int getStandort_idstandort() {
      return standort_idstandort;
   }
   /**
    * Returns the value of the "typ" attribute.
    *
    * @return The value of the "typ" attribute.
    */
   public String getTyp() {
      return typ;
   }
   /**
    * Returns the value of the "fahrzeug_in_saison" attribute.
    *
    * @return The value of the "fahrzeug_in_saison" attribute.
    */
   public List<Fahrzeug_in_saison> getFahrzeug_in_saison() {
      return fahrzeug_in_saison;
   }
   
   /**
    * Returns the value of the "mietfahrzeugs" attribute.
    *
    * @return The value of the "mietfahrzeugs" attribute.
    */
   public List<Mietfahrzeug> getMietfahrzeugs() {
      return mietfahrzeugs;
   }
   
   /**
    * Returns the value of the "standort" attribute.
    *
    * @return The value of the "standort" attribute.
    */
   public Standort getStandort() {
      return standort;
   }
   
   /**
    * Sets the value of the "fahrgestellNr" attribute.
    *
    * @param fahrgestellNr
    *     The value of the "fahrgestellNr" attribute.
    */
   public void setFahrgestellNr(int fahrgestellNr) {
      this.fahrgestellNr = fahrgestellNr;
   }
   /**
    * Sets the value of the "marke" attribute.
    *
    * @param marke
    *     The value of the "marke" attribute.
    */
   public void setMarke(String marke) {
      this.marke = marke;
   }
   /**
    * Sets the value of the "standort_idstandort" attribute.
    *
    * @param standort_idstandort
    *     The value of the "standort_idstandort" attribute.
    */
   public void setStandort_idstandort(int standort_idstandort) {
      this.standort_idstandort = standort_idstandort;
   }
   /**
    * Sets the value of the "typ" attribute.
    *
    * @param typ
    *     The value of the "typ" attribute.
    */
   public void setTyp(String typ) {
      this.typ = typ;
   }
   /**
    * Sets the value of the "fahrzeug_in_saison" attribute.
    *
    * @param fahrzeug_in_saison"
    *     The value of the "fahrzeug_in_saison" attribute.
    */
   public void setFahrzeug_in_saison(List<Fahrzeug_in_saison> fahrzeug_in_saison) {
      this.fahrzeug_in_saison = fahrzeug_in_saison;
   }

   /**
    * Sets the value of the "mietfahrzeugs" attribute.
    *
    * @param mietfahrzeugs"
    *     The value of the "mietfahrzeugs" attribute.
    */
   public void setMietfahrzeugs(List<Mietfahrzeug> mietfahrzeugs) {
      this.mietfahrzeugs = mietfahrzeugs;
   }

   /**
    * Sets the value of the "standort" attribute.
    *
    * @param standort"
    *     The value of the "standort" attribute.
    */
   public void setStandort(Standort standort) {
      this.standort = standort;
   }

}