/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package womomodel;


import java.util.Date;
import womomodel.Fahrzeug;
import womomodel.Kunde;
import womomodel.Saison;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:50021/WoMoService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Mietfahrzeug {

    private Date datumBis;
    private Date datumVon;
    private int fahrgestellNr;
    private int idKunde;
    private int idSaison;
    private Fahrzeug fahrzeug;
    private Kunde kunde;
    private Saison saison;

    /**
     * Constructor without parameter.
     * 
     */
    public Mietfahrzeug() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Mietfahrzeug(int fahrgestellNr, int idKunde, int idSaison) {
        this();
        this.fahrgestellNr = fahrgestellNr;
        this.idKunde = idKunde;
        this.idSaison = idSaison;
    }

   /**
    * Returns the value of the "datumBis" attribute.
    *
    * @return The value of the "datumBis" attribute.
    */
   public Date getDatumBis() {
      return datumBis;
   }
   /**
    * Returns the value of the "datumVon" attribute.
    *
    * @return The value of the "datumVon" attribute.
    */
   public Date getDatumVon() {
      return datumVon;
   }
   /**
    * Returns the value of the "fahrgestellNr" attribute.
    *
    * @return The value of the "fahrgestellNr" attribute.
    */
   public int getFahrgestellNr() {
      return fahrgestellNr;
   }
   /**
    * Returns the value of the "idKunde" attribute.
    *
    * @return The value of the "idKunde" attribute.
    */
   public int getIdKunde() {
      return idKunde;
   }
   /**
    * Returns the value of the "idSaison" attribute.
    *
    * @return The value of the "idSaison" attribute.
    */
   public int getIdSaison() {
      return idSaison;
   }
   /**
    * Returns the value of the "fahrzeug" attribute.
    *
    * @return The value of the "fahrzeug" attribute.
    */
   public Fahrzeug getFahrzeug() {
      return fahrzeug;
   }
   
   /**
    * Returns the value of the "kunde" attribute.
    *
    * @return The value of the "kunde" attribute.
    */
   public Kunde getKunde() {
      return kunde;
   }
   
   /**
    * Returns the value of the "saison" attribute.
    *
    * @return The value of the "saison" attribute.
    */
   public Saison getSaison() {
      return saison;
   }
   
   /**
    * Sets the value of the "datumBis" attribute.
    *
    * @param datumBis
    *     The value of the "datumBis" attribute.
    */
   public void setDatumBis(Date datumBis) {
      this.datumBis = datumBis;
   }
   /**
    * Sets the value of the "datumVon" attribute.
    *
    * @param datumVon
    *     The value of the "datumVon" attribute.
    */
   public void setDatumVon(Date datumVon) {
      this.datumVon = datumVon;
   }
   /**
    * Sets the value of the "fahrgestellNr" attribute.
    *
    * @param fahrgestellNr
    *     The value of the "fahrgestellNr" attribute.
    */
   public void setFahrgestellNr(int fahrgestellNr) {
      this.fahrgestellNr = fahrgestellNr;
   }
   /**
    * Sets the value of the "idKunde" attribute.
    *
    * @param idKunde
    *     The value of the "idKunde" attribute.
    */
   public void setIdKunde(int idKunde) {
      this.idKunde = idKunde;
   }
   /**
    * Sets the value of the "idSaison" attribute.
    *
    * @param idSaison
    *     The value of the "idSaison" attribute.
    */
   public void setIdSaison(int idSaison) {
      this.idSaison = idSaison;
   }
   /**
    * Sets the value of the "fahrzeug" attribute.
    *
    * @param fahrzeug"
    *     The value of the "fahrzeug" attribute.
    */
   public void setFahrzeug(Fahrzeug fahrzeug) {
      this.fahrzeug = fahrzeug;
   }

   /**
    * Sets the value of the "kunde" attribute.
    *
    * @param kunde"
    *     The value of the "kunde" attribute.
    */
   public void setKunde(Kunde kunde) {
      this.kunde = kunde;
   }

   /**
    * Sets the value of the "saison" attribute.
    *
    * @param saison"
    *     The value of the "saison" attribute.
    */
   public void setSaison(Saison saison) {
      this.saison = saison;
   }

}