/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package womomodel;


import java.util.Date;
import java.util.List;
import womomodel.Fahrzeug_in_saison;
import womomodel.Mietfahrzeug;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:50021/WoMoService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Saison {

    private Date datumBis;
    private Date datumVon;
    private int idSaison;
    private String name;
    private List<Fahrzeug_in_saison> fahrzeug_in_saison;
    private List<Mietfahrzeug> mietfahrzeugs;

    /**
     * Constructor without parameter.
     * 
     */
    public Saison() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Saison(int idSaison) {
        this();
        this.idSaison = idSaison;
    }

   /**
    * Returns the value of the "datumBis" attribute.
    *
    * @return The value of the "datumBis" attribute.
    */
   public Date getDatumBis() {
      return datumBis;
   }
   /**
    * Returns the value of the "datumVon" attribute.
    *
    * @return The value of the "datumVon" attribute.
    */
   public Date getDatumVon() {
      return datumVon;
   }
   /**
    * Returns the value of the "idSaison" attribute.
    *
    * @return The value of the "idSaison" attribute.
    */
   public int getIdSaison() {
      return idSaison;
   }
   /**
    * Returns the value of the "name" attribute.
    *
    * @return The value of the "name" attribute.
    */
   public String getName() {
      return name;
   }
   /**
    * Returns the value of the "fahrzeug_in_saison" attribute.
    *
    * @return The value of the "fahrzeug_in_saison" attribute.
    */
   public List<Fahrzeug_in_saison> getFahrzeug_in_saison() {
      return fahrzeug_in_saison;
   }
   
   /**
    * Returns the value of the "mietfahrzeugs" attribute.
    *
    * @return The value of the "mietfahrzeugs" attribute.
    */
   public List<Mietfahrzeug> getMietfahrzeugs() {
      return mietfahrzeugs;
   }
   
   /**
    * Sets the value of the "datumBis" attribute.
    *
    * @param datumBis
    *     The value of the "datumBis" attribute.
    */
   public void setDatumBis(Date datumBis) {
      this.datumBis = datumBis;
   }
   /**
    * Sets the value of the "datumVon" attribute.
    *
    * @param datumVon
    *     The value of the "datumVon" attribute.
    */
   public void setDatumVon(Date datumVon) {
      this.datumVon = datumVon;
   }
   /**
    * Sets the value of the "idSaison" attribute.
    *
    * @param idSaison
    *     The value of the "idSaison" attribute.
    */
   public void setIdSaison(int idSaison) {
      this.idSaison = idSaison;
   }
   /**
    * Sets the value of the "name" attribute.
    *
    * @param name
    *     The value of the "name" attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   /**
    * Sets the value of the "fahrzeug_in_saison" attribute.
    *
    * @param fahrzeug_in_saison"
    *     The value of the "fahrzeug_in_saison" attribute.
    */
   public void setFahrzeug_in_saison(List<Fahrzeug_in_saison> fahrzeug_in_saison) {
      this.fahrzeug_in_saison = fahrzeug_in_saison;
   }

   /**
    * Sets the value of the "mietfahrzeugs" attribute.
    *
    * @param mietfahrzeugs"
    *     The value of the "mietfahrzeugs" attribute.
    */
   public void setMietfahrzeugs(List<Mietfahrzeug> mietfahrzeugs) {
      this.mietfahrzeugs = mietfahrzeugs;
   }

}