/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package womomodel;


import java.util.List;
import womomodel.Mietfahrzeug;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:50021/WoMoService.svc/$metadata">Metadata of the target OData service</a>
*
*/
public class Kunde {

    private int idKunde;
    private String nachname;
    private String ort;
    private int plz;
    private String strasse;
    private String vorname;
    private List<Mietfahrzeug> mietfahrzeugs;

    /**
     * Constructor without parameter.
     * 
     */
    public Kunde() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Kunde(int idKunde) {
        this();
        this.idKunde = idKunde;
    }

   /**
    * Returns the value of the "idKunde" attribute.
    *
    * @return The value of the "idKunde" attribute.
    */
   public int getIdKunde() {
      return idKunde;
   }
   /**
    * Returns the value of the "nachname" attribute.
    *
    * @return The value of the "nachname" attribute.
    */
   public String getNachname() {
      return nachname;
   }
   /**
    * Returns the value of the "ort" attribute.
    *
    * @return The value of the "ort" attribute.
    */
   public String getOrt() {
      return ort;
   }
   /**
    * Returns the value of the "plz" attribute.
    *
    * @return The value of the "plz" attribute.
    */
   public int getPlz() {
      return plz;
   }
   /**
    * Returns the value of the "strasse" attribute.
    *
    * @return The value of the "strasse" attribute.
    */
   public String getStrasse() {
      return strasse;
   }
   /**
    * Returns the value of the "vorname" attribute.
    *
    * @return The value of the "vorname" attribute.
    */
   public String getVorname() {
      return vorname;
   }
   /**
    * Returns the value of the "mietfahrzeugs" attribute.
    *
    * @return The value of the "mietfahrzeugs" attribute.
    */
   public List<Mietfahrzeug> getMietfahrzeugs() {
      return mietfahrzeugs;
   }
   
   /**
    * Sets the value of the "idKunde" attribute.
    *
    * @param idKunde
    *     The value of the "idKunde" attribute.
    */
   public void setIdKunde(int idKunde) {
      this.idKunde = idKunde;
   }
   /**
    * Sets the value of the "nachname" attribute.
    *
    * @param nachname
    *     The value of the "nachname" attribute.
    */
   public void setNachname(String nachname) {
      this.nachname = nachname;
   }
   /**
    * Sets the value of the "ort" attribute.
    *
    * @param ort
    *     The value of the "ort" attribute.
    */
   public void setOrt(String ort) {
      this.ort = ort;
   }
   /**
    * Sets the value of the "plz" attribute.
    *
    * @param plz
    *     The value of the "plz" attribute.
    */
   public void setPlz(int plz) {
      this.plz = plz;
   }
   /**
    * Sets the value of the "strasse" attribute.
    *
    * @param strasse
    *     The value of the "strasse" attribute.
    */
   public void setStrasse(String strasse) {
      this.strasse = strasse;
   }
   /**
    * Sets the value of the "vorname" attribute.
    *
    * @param vorname
    *     The value of the "vorname" attribute.
    */
   public void setVorname(String vorname) {
      this.vorname = vorname;
   }
   /**
    * Sets the value of the "mietfahrzeugs" attribute.
    *
    * @param mietfahrzeugs"
    *     The value of the "mietfahrzeugs" attribute.
    */
   public void setMietfahrzeugs(List<Mietfahrzeug> mietfahrzeugs) {
      this.mietfahrzeugs = mietfahrzeugs;
   }

}