//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoMoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fahrzeug()
        {
            this.Mietfahrzeugs = new HashSet<Mietfahrzeug>();
            this.fahrzeug_in_saison = new HashSet<fahrzeug_in_saison>();
        }
    
        public int fahrgestellNr { get; set; }
        public Nullable<int> standort_idstandort { get; set; }
        public string marke { get; set; }
        public string typ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mietfahrzeug> Mietfahrzeugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fahrzeug_in_saison> fahrzeug_in_saison { get; set; }
        public virtual Standort Standort { get; set; }
    }
}
