//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoMoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kunde()
        {
            this.Mietfahrzeugs = new HashSet<Mietfahrzeug>();
        }
    
        public int IdKunde { get; set; }
        public string vorname { get; set; }
        public string nachname { get; set; }
        public string strasse { get; set; }
        public Nullable<int> plz { get; set; }
        public string ort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mietfahrzeug> Mietfahrzeugs { get; set; }
    }
}
