//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoMoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saison
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saison()
        {
            this.fahrzeug_in_saison = new HashSet<fahrzeug_in_saison>();
            this.Mietfahrzeugs = new HashSet<Mietfahrzeug>();
        }
    
        public int idSaison { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> datumVon { get; set; }
        public Nullable<System.DateTime> datumBis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fahrzeug_in_saison> fahrzeug_in_saison { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mietfahrzeug> Mietfahrzeugs { get; set; }
    }
}
