//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoMoService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WoMoEntities : DbContext
    {
        public WoMoEntities()
            : base("name=WoMoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fahrzeug> Fahrzeugs { get; set; }
        public virtual DbSet<fahrzeug_in_saison> fahrzeug_in_saison { get; set; }
        public virtual DbSet<Kunde> Kundes { get; set; }
        public virtual DbSet<Mietfahrzeug> Mietfahrzeugs { get; set; }
        public virtual DbSet<Saison> Saisons { get; set; }
        public virtual DbSet<Standort> Standorts { get; set; }
    }
}
